version: '3'

volumes:
  django_query_table_local_postgres_data: {}
  django_query_table_local_postgres_data_backups: {}

services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: django_query_table_local_django
    container_name: django_query_table_local_django
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: django_query_table_production_postgres
    container_name: django_query_table_local_postgres
    volumes:
      - django_query_table_local_postgres_data:/var/lib/postgresql/data
      - django_query_table_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  docs:
    image: django_query_table_local_docs
    container_name: django_query_table_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./django_query_table:/app/django_query_table:z
    ports:
      - '9000:9000'
    command: /start-docs

  redis:
    image: docker.io/redis:6
    container_name: django_query_table_local_redis

  celeryworker:
    <<: *django
    image: django_query_table_local_celeryworker
    container_name: django_query_table_local_celeryworker
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: django_query_table_local_celerybeat
    container_name: django_query_table_local_celerybeat
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    image: django_query_table_local_flower
    container_name: django_query_table_local_flower
    ports:
      - '5555:5555'
    command: /start-flower
